---

type: enum("mdrive")
environment:
  ENGINEER: str()
  PREFIX: str()
  SYS_IOC: str()
  IP_PORT: int()

devices: list(include('device'), min=1)

---

device:
  host: any(ip(), hostname())
  io_port: regex("^P\\d+$")
  Sys: str()
  Dev: str()
  MRES: num()
  EGU: str()
  DESC: str()
  ALIAS: str()
