---

type: enum("mdrive")
environment:
  ENGINEER: str()
  PREFIX: str()
  SYS_IOC: str()
  IP_PORT: int()
  SYS: str()
  MRES: num()
  EGU: str()

devices: list(include('device'), min=1)

---

device:
  host: any(ip(), hostname())
  io_port: regex("^P\\d+$")
  Sys: str(required=False)
  Dev: str()
  MRES: num(required=False)
  EGU: str(required=False)
  DESC: str(required=False)
  ALIAS: str(required=False)
