---

- name: Fail if module name is not set
  ansible.builtin.fail:
    msg: "Module name must be set"
  when: install_module_name is not defined

- name: Set facts
  ansible.builtin.include_tasks: set-facts.yml

- name: Create modules directory if it doesn't exist
  ansible.builtin.file:
    path: "{{ install_module_install_dir }}"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    state: "directory"
    mode: "0775"

- name: Get list of required system packages
  ansible.builtin.set_fact:
    install_module_pkg_deps: "{{ install_module_default_pkg_deps }}"

- name: Add any module-specific required packages
  ansible.builtin.set_fact:
    install_module_pkg_deps:
      "{{ install_module_pkg_deps
      | union(install_module_config.pkg_deps) }}"
  when: install_module_config.pkg_deps is defined

- name: Install any required system packages
  ansible.builtin.dnf:
    name: "{{ install_module_pkg_deps }}"
    state: present

- name: Check if module has already been cloned
  ansible.builtin.stat:
    path: "{{ install_module_dir }}/.git"
  register: install_module_cloned

- name: If cloned, ensure ownership and permissions are set correctly
  ansible.builtin.command:
    "chown -R {{ host_config.softioc_user }}:{{ host_config.softioc_group }} {{ install_module_dir }}" # noqa command-instead-of-module
  changed_when: true
  when: install_module_cloned.stat.exists

# Perform the clone and build as the softioc user
- name: Clone, checkout, and build the module
  become: true
  become_user: "{{ host_config.softioc_user }}"
  block:
    - name: Clone the module and update configure files
      ansible.builtin.include_tasks: clone-module.yml

    - name: Compile the module
      ansible.builtin.shell:
        # yamllint disable rule:line-length
        cmd: "{{ install_module_compilation_command }}" # noqa: command-instead-of-shell
        # yamllint enable rule:line-length
        chdir: "{{ install_module_dir }}"
      register: install_module_compile_result
      changed_when: install_module_compile_result.rc == 0
      when: not (install_module_skip_compilation | bool)

# TODO: Check if this is necessary, since we're cloning and building as the softioc_user, but it doesn't hurt to be sure
- name: Ensure module directory is owned by softioc_user, after compilation
  ansible.builtin.command:
    "chown -R {{ host_config.softioc_user }}:{{ host_config.softioc_group }} {{ install_module_dir }}" # noqa command-instead-of-module
  changed_when: true

- name: Add module to dict mapping module names to paths
  ansible.builtin.set_fact:
    install_module_installed:
      "{{ install_module_installed |
          combine({install_module_config.name | upper:
                    install_module_dir}) }}"

- name: Add module to installed modules list
  ansible.builtin.set_fact:
    install_module_installed_list:
      "{{ install_module_installed_list + [install_module_name] }}"

- name: Set path of installed leaf module
  ansible.builtin.set_fact:
    install_module_leaf_module_path: "{{ install_module_dir }}"

- name: If specified, set installed leaf module executable
  ansible.builtin.set_fact:
    install_module_leaf_executable:
      "{{ install_module_config.executable }}"
  when: install_module_config.executable is defined
