---
type: enum("base_stream_device")
environment:
  ENGINEER: str()
connections: map(include('connection'), key=str())

---
connection:
  type: enum("IP", "Serial")
  connection: str()
  output_eos: str()
  input_eos: str()
  serial_settings: include('serial_setting', required=False)

serial_setting:
  baud: enum(1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200)
  bits: enum(8, 7, 6, 5)
  parity: enum('none', 'even', 'odd')
  stop: enum(1, 2)
  clocal: enum('Y', 'N')
  crtscts: enum('N', 'Y')
  ixon: enum('N', 'Y')
  ixoff: enum('N', 'Y')
  ixany: enum('N', 'Y')
