---
- name: Install acmi2 base startup commands
  ansible.builtin.template:
    src: templates/base.cmd.j2
    dest: "{{ deploy_ioc_ioc_directory }}/iocBoot/base.cmd"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"

- name: Create acmi2 data and support directories
  ansible.builtin.file:
    path: "{{ deploy_ioc_ioc_directory }}/{{ item }}"
    state: directory
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "02775"
  loop:
    - Correction
    - COW
    - gui
    - PM
    - python
    - settings

- name: Copy files from acmi2 source directories
  ansible.builtin.copy:
    src: "{{ deploy_ioc_required_module_path }}/{{ item }}/"
    dest: "{{ deploy_ioc_ioc_directory }}/{{ item }}/"
    remote_src: true
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"
  loop:
    - Correction
    - COW
    - gui
    - PM
    - python
    - settings
