---

gpio_ex1:
  type: "elio"
  terminals:
    - POS: 1
      MODEL: "EL3068"
    - POS: 2
      MODEL: "EL4008"
    - POS: 3
      MODEL: "EL1808"
    - POS: 4
      MODEL: "EL1808"
    - POS: 5
      MODEL: "EL2808"
    - POS: 6
      MODEL: "EL2808"
    - POS: 7
      MODEL: "EL3068"
    - POS: 8
      MODEL: "EL1124"
    - POS: 9
      MODEL: "EL3008"
      CHAN_SPECIFIC_CONFIG:
        1: {"LINR": "SLOPE", "EGU": "V"}
        2: {"LINR": "SLOPE", "EGU": "mA"}

  # SYS and DEV: used to generate prefix for each device
  # PREFIX: used for IOC-specific PVs
  # HOST may be an IP address or host name
  # EK9K: port name
  environment:
    SYS: "XF:31ID1-ES"
    DEV: "GPIO:1"
    EK9K: EK9K1
    HOST: 10.69.58.101
    PREFIX: "XF:31ID1-CT{IOC:GPIO1}"
    ENGINEER: "H. Xu"    # Your name/contact info
