---
adeiger_a7b25dc:
  name: ADEiger
  url: https://github.com/areadetector/ADEiger
  include_base_ad_config: true
  version: a7b25dc
  executable: eigerDetectorApp
  module_deps:
    - adcore_5860bd3
    - adcompvision_9750d13
    - adpluginbar_448d96b
    - ffmpeg_server_07c570f
  pkg_deps:
    - zeromq-devel
