---

adtimepix3_15009fe:
  name: ADTimePix3
  version: 15009fe

  url: https://github.com/areaDetector/ADTimePix3
  include_base_ad_config: true
  pkg_deps:
    - curl-devel
  module_deps:
    - adcore_60080dc
    - adsupport_6acf83f
