---
xspress3_5f459a1:
  name: xspress3
  version: 5f459a1
  url: https://github.com/epics-modules/xspress3
  include_base_ad_config: true
  overwrite_config_site: true
  module_deps:
    - adcore_5860bd3
