---
xspress3_5f459a1:
  # Commit: https://github.com/epics-modules/xspress3/commit/5f459a152b65218515bb573c9abb684bcc11f8a2
  # Date: May 29, 2026
  # In versions: None
  name: xspress3
  version: 5f459a1
  url: https://github.com/epics-modules/xspress3
  include_base_ad_config: true
  overwrite_config_site: true
  module_deps:
    - adcore_5860bd3
