---

deploy_ioc_use_common: true
deploy_ioc_use_ad_common: false
deploy_ioc_required_module: dcpses150_7fe969e
deploy_ioc_executable: dcps-es150
deploy_ioc_template_root_path: "{{ install_module_leaf_module_path }}"
