---

type: enum("adeiger")

detector_model: enum("eiger1", "eiger2", "pilatus4", "selun")

# Configure local port if Eiger is connected directly to the server.
# Comment out otherwise.
adeiger_local_intf_mac: str(required=False)
adeiger_local_intf_ip: any(ip(), hostname(), required=False)

environment:
  ENGINEER: str()
  PREFIX: str()
  DCU_IP: any(ip(), hostname())
  STREAM_IP: any(ip(), hostname(), required=False)

  XSIZE: int()
  YSIZE: int()
  QSIZE: int()

  # The maximum number of frames buffered in the NDPluginCircularBuff plugin
  CBUFFS: int()
  NELEMENTS: int()
