---
type: enum("turbopmac")
environment:
  ENGINEER: str()
  PREFIX: str()
  CT_PREFIX: str()
  IOC_ASYN: str()
  IP_PORT: str()
  CONTROLLER_IP: ip()
  CONTROLLER_PORT: str()
  NUM_AXES: int()

disable_lim_axes: list(any(enum("all"), int()), required=False)

open_loop_axes:
  pattern: list(enum("axis_num", "encoder_axis_num"), min=2, max=2)
  instances: list(list(int(), min=2, max=2))

coord_systems:
  pattern: list(enum("cs_num"), list(list(enum("virtual_axis1", "scale_factor1"), min=2, max=2), list(enum("virtual_axis2", "scale_factor2"), min=2, max=2), min=2, max=2), min=3, max=3)  # yamllint disable-line rule:line-length
  instances: list(list(int(), list(list(num(), min=2, max=2), min=2, max=2)), min=3, max=3) # yamllint disable-line rule:line-length

substitutions:
  motor: list(include("motor_substitution"), min=1, max=1)
  motorstatus: list(include("status_substitution"), min=1, max=2)
  pmac_asyn_motor: list(include("pmac_asyn_motor_substitution"), min=1, max=1)

motor_substitution:
  filepath: enum("$(TPMAC)/db/motor.db")
  pattern: list(enum("P", "M", "MOTOR", "PORT", "ADDR", "DESC", "DTYP", "MRES", "EGU", "PREC", "ALIAS"), min=11, max=11)) # yamllint disable-line rule:line-length
  instances: list(list(str(), int(), min=11, max=11), min=1)

status_substitution:
  filepath: enum("$(TPMAC)/db/motorstatus.db", "$(TPMAC)/db/pmacStatusAxis.db")
  pattern: list(enum("SYS", "DEV", "PORT", "AXIS"), min=4, max=4))
  instances: list(list(str(), int(), min=4, max=4), min=1)

pmac_asyn_motor_substitution:
  filepath: enum("$(TPMAC)/db/pmac_asyn_motor.db")
  pattern: list(enum("SYS", "DEV", "MOTOR", "SPORT", "ADDR", "DESC", "DTYP", "PREC", "EGU"), min=9, max=9)) # yamllint disable-line rule:line-length
  instances: list(list(str(), int(), min=9, max=9), min=1)
