---

type: enum("mrftiming")
environment:
  IP: any(ip(), hostname())
  P: str()
  R: str(required=False)
  ENGINEER: str(required=False)
  PREFIX: str(required=False)
  IOC_PREFIX: str(required=False)
  MRFTIMING: str(required=False)
  EPICS_MRF: str(required=False)
  UO_01: str(required=False)
  UO_23: str(required=False)
  UO_01FD: str(required=False)
  UO_23FD: str(required=False)
  TB_01: str(required=False)
  TB_23: str(required=False)
  TB_45: str(required=False)
  TB_67: str(required=False)
  TB_89: str(required=False)
  TB_1011: str(required=False)
  TB_1213: str(required=False)
  TB_1415: str(required=False)
