---
name: Run Superlinter

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter@85f7611e0f7b53c8573cca84aa0ed4344f6f6a4d # v7.2.1
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YAML_ERROR_ON_WARNING: true
          VALIDATE_YAML_PRETTIER: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_MARKDOWN_PRETTIER: false

  run_ansible_lint:
    name: Run ansible-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core==2.14.1 ansible-lint

          #- name: Install ansible galaxy requirements
          #run: |
          #ansible-galaxy install -r collections/requirements.yml

      - name: Lint playbook
        run: |
          ansible-lint -c .ansible-lint
